### ISSUE TITLE
move bharat-patodi.md to first-contributions/bharat-patodi.md

### ISSUE THREAD

**Issue by Subskii** [the-fast-tracked-programmer/first-contributions#61]
fixes #11 

missed this in the initial review @bharat-patodi. Oops!

Great practice for following up :)

Can assign you once you've accepted the invite too :smiley:

**Comment by bharat-patodi** [comment]
I just joined in @Subskii 
Sorry about this!
This oversight has occurred because I mistook the folder name to be the repository name. 
They are both **first-contributions**.
Should I create a fresh PR for moving my file in the internal folder?

![image](https://user-images.githubusercontent.com/16771172/132090447-2970219d-70e1-41ee-9266-4611f3d6b23b.png)

**Comment by Subskii** [comment]
Yeah haha know what you mean I missed this in the initial review too :)

A new pull request linked to this issue would be perfect!

And perhaps we need to make the readme clearer too huh?
